### ISSUE TITLE
sensirion SFM3000 flow sensor with arduino uno via i2c communication problem...

### ISSUE THREAD

**Issue by MohamedFarghaly153** [winkj/arduino-sflow#4]
[flow report.docx](https://github.com/winkj/arduino-sflow/files/862341/flow.report.docx)

 I connected the I2C communication and tested the connectivity with I2C scanner code.
now I'm using your code for reading the flow (SFLOW) , the serial monitor screen results ''Failed to read from I2C 4''.
find attached the out of the sample programs

**Comment by winkj** [comment]
Hi,

It appears the SFM3000 is using a different protocol, and would therefore not work with arduino-sflow. Unfortunately, I don't have access to an SFM3000 right now, so can't test it.

The SFM3000's I2C protocol is documented here:
 https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/5_Mass_Flow_Meters/Sensirion_Mass_Flow_Meters_SFM3000_I2C_Functional_Description_V1.1.pdf

Command '0x1000' triggers continuous measurements (Section 4 of the app note), and you should then be able to read back three bytes (two bytes data, 1 byte CRC; see section 4.1).

I'll try to get access to a SFM3000, but for now, I'd recommend implementing the I2C as described above; it should be fairly simple compared to the arduino-sflow driver.

**Comment by MohamedFarghaly153** [comment]
dear winkj, 
thanks for your interest, but till now i couldn't read the flow from the sensor, PLZZZZZZZZZZZZ I need your support

**Comment by winkj** [comment]
Hi MohamedFarghaly153,

I don't have an SFM3000 yet. Can you share what you've tried so far?

**Comment by winkj** [comment]
Hi MohamedFarghaly153,

Did you have any time to prepare the code you've written so far? You can post it on https://gist.github.com/

**Comment by charbelmetrot** [comment]
hi MohamedFarghaly153,

What did you do to make your code work correctly?
can you help me please, I have the same problem you have got.

**Comment by winkj** [comment]
The SFM3000 is currently not supported
