### ISSUE TITLE
SFM3000 circuit

### ISSUE THREAD

**Issue by charbelmetrot** [winkj/arduino-sflow#6]
I have a problem, i'm using the SFM3000 with the code you have, but I can;t read the data from the sensor,
all cases of not able to reading the data are working, but  when i need to read data nothing is happening.
Can you help me please.
And give me the circuit you have worked on for this code please.

Thank you!

**Comment by winkj** [comment]
Hi there, 

At this point, I fear the SFM3000 is not supported; I will need to look into it, but it's using a different set of I2C commands. There is documentation and sample code available directly from Sensirion, so if you have time to port that to Arduino please submit a merge request!

**Comment by charbelmetrot** [comment]
I mean i want the connections that you have used to connect the SFM3000 to the arduino.
Did you used the analogic ports of the arduino or the SDA and the SCL?

**Comment by winkj** [comment]
Ah, I see. According to the datasheet, it's an I2C part, so used SDA/SCL on the Arduino
